A
Altu-Bitu-3/Altu-Bitu-YiJeongMin pull request #2
Opened 2022-09-11 18:03 UTC by JisforJelly

맵과 셋 과제 제출합니다!
기존 제출: 11723, 14425, 14911, 2910

풀었지만 틀린 문제가 있는데, 그래도 제출하면 되는지 궁금합니다.

2022-09-12 06:34 UTC, dbswn requested changes
안녕하세요 정민님!!😊 과제 제출하시느라 수고 많으셨습니다! 
혹시 풀었지만 틀린 문제가 2910번이 맞으실까요?? 도움이 될 수 있는 부분 적어 두었으니 코멘트 확인하시고 수정해주세요!! 혹시나 궁금하신 점이 있으시면 호출해 주셔도 좋습니다! 😄

**P1은 반드시 수정하셔야 하는 부분이니 코드 수정하시고 리뷰어 호출 부탁드려요~!**

2022-09-12 06:34 UTC, dbswn commented on 09월 06일 - 맵과 셋/2910.cpp
> +                arr[i].priority -= i;
**P1**
여기에서 arr의 range가 넘어가는 부분에 접근해 오류가 나는 것 같습니다.
2입력 -> arr[0] =  (2,1,2)
1입력 -> arr[1] =  (1,1,1)
2입력 -> arr[0] = (2,2,2)
1입력 -> i=3, j=0  일 때 else문으로 들어가서 오류

n을 입력받을 때마다 arr을 앞에서부터 탐색하고 숫자가 다르면 else문으로 들어가기에 오류가 납니다!

2022-09-12 06:34 UTC, dbswn commented on 09월 06일 - 맵과 셋/2910.cpp
> +            }
**P1**
n을 입력받고 반복문으로 arr을 앞에서부터 탐색해 `arr[j].number == n` 를 기준으로 다음에 해야 할 행동을 구분해주셨는데요. 앞에서부터 탐색하지 않고 입력받은 n을 key값으로 n의 정보에 접근하는 방법은 어떨까요?? 이번 단원이 map과 set인만큼 두 구조의 개념과 사용했을 때의 장점에 대해서 생각해보면 좋을 것 같네요!

2022-09-12 09:31 UTC, flowersayo reviewed
**14425 코드 리뷰 완료**

안녕하세요 정민님 !!😊
코드가 정말 깔끔해서 리뷰하기 너무 좋았습니다!
변수이름 등 사소한 부분만 커멘트 남겼네요 ㅎㅎ
p1 커멘트는 꼭 수정해주셨으면 하는 부분이고 p2, p3는 참고만 해주셔도 괜찮습니다
수고하셨습니다🥰

2022-09-12 09:31 UTC, flowersayo commented on 09월 06일 - 맵과 셋/14425.cpp
> +    {
p3. N번 반복을 시행하는 부분은 while문을 사용하면 조금더 간결하게 작성해볼 수 있을 것 같아요!

2022-09-12 09:31 UTC, flowersayo commented on 09월 06일 - 맵과 셋/14425.cpp
> +    }
find 라는 함수를 잘 찾아서 활용해주셨네요!🤗
set은 이진트리 구조로 이루어져 있기에 원소 탐색에 걸리는 시간은 O(logN)이죠!
만일 본 문제를 set,map 이 아닌 다른 컨테이너로 해결하려고 했었다면 시간초과가 발생했을 거에요!

2022-09-12 09:31 UTC, flowersayo commented on 09월 06일 - 맵과 셋/14425.cpp
> +    int N, M;
p2. 저희 튜터링에서는 상수만 대문자 표기를 허용하고 있어요! 소문자로 바꾸어줄까요?

2022-09-12 10:41 UTC, flowersayo commented
> 맵과 셋 과제 제출합니다! 기존 제출: 11723, 14425, 14911, 2910
> 
> 풀었지만 틀린 문제가 있는데, 그래도 제출하고 코드리뷰를 하면 되는건지 궁금합니다!

넵! 일단 시도해보신 문제가 있으시다면 올려주세요! 
문제 접근방식 확인해보고 피드백 남겨드릴 예정입니다!
작년에는 맞았습니다 를 받지 못한 문제이더라도 제출시에 같이 올려드리고 
틀린 원인을 짚어주시면 튜티님께서 다음날까지 코드를 수정해서 재 업로드 해주시면 제출처리를 해드렸었습니다
이부분은 튜터님들끼리 상의해보고 다시 전달드리겠습니다 :)

2022-09-12 11:22 UTC, Dong-droid commented
**P3 11723 코드 리뷰 완료**
너무 잘 푸셨네요!!
이 문제를 푸는 방법은 여러가지(배열, 비트마스킹)이 있는데 그것도 나중에 풀이를 한 번 보시는 것도 좋을 것 같습니다.
수고하셨습니다!

2022-09-12 11:24 UTC, Dong-droid commented on 09월 06일 - 맵과 셋/11723.cpp
> +            continue;
P3) 여기까지 continue가 필요하지 않은 것 같아요!

2022-09-12 17:20 UTC, 0321minji commented
**14911 코드리뷰 완료**
안녕하세요 수민님! 전체적인 틀은 맞게 작성해주셨습니다!👍
코드를 조금만 수정하면 정답이 될 것 같아서 도움이 될 만한 코멘트 조금 남기니 참고해주시고 수정 해주세요!
수고하셨습니다 :)

2022-09-13 13:40 UTC, JisforJelly commented
맵과 셋 과제 제출합니다!
기존 제출: 11723, 14425, 14911, 2910
추가 제출: 10757, 9375

2910번은 조금 더 고민하고 풀어보고싶습니다!!

2022-09-13 14:07 UTC, kwakrhkr59 commented
**[추가제출 확인 완료]**
안녕하세요 정민님~ 추가제출해주신 코드 확인 완료됐습니다:)
내가 직접 문제를 푸는 것 뿐만 아니라 다른 사람의 코드를 읽고 해석해보는 것도 정말 많은 도움이 되니 앞으로도 저희의 샘플코드와 함께 공부해주시면 좋을 것 같습니다😊
이번 과제도 정말 수고 많으셨습니다~

2022-09-14 16:35 UTC, JisforJelly commented
잉

2022-09-14 16:36 UTC, closed without merging